# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2

project_name: extract-sbom

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/extract-sbom
    binary: extract-sbom
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/TomTonic/extract-sbom/internal/buildinfo.ReleaseVersion={{.Version}}

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^deps-upd:'
      - Merge pull request
      - Merge branch
